# Generated by Django 4.2.3 on 2023-10-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0002_userprofile_secondemail_userprofile_secondphone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='secondEmail',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
